//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienesCompuestos
    {
        public int BienId { get; set; }
        public int CompuestosId { get; set; }
        public double Cantidad { get; set; }
    
        public virtual Bienes Bienes { get; set; }
        public virtual Bienes Bienes1 { get; set; }
    }
}
