//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bienes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bienes()
        {
            this.BienesCompuestos = new HashSet<BienesCompuestos>();
            this.BienesCompuestos1 = new HashSet<BienesCompuestos>();
            this.Inventario = new HashSet<Inventario>();
            this.PedidosProveedoresDetalle = new HashSet<PedidosProveedoresDetalle>();
            this.PresupuestosClientesDetalle = new HashSet<PresupuestosClientesDetalle>();
            this.Cualidades = new HashSet<Cualidades>();
            this.Historicos = new HashSet<Historicos>();
        }
    
        public int Id { get; set; }
        public string CodBien { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int FamiliaId { get; set; }
        public int IVAId { get; set; }
        public double Precio { get; set; }
        public double PrecioBase { get; set; }
        public double Descuento { get; set; }
        public int EstadoId { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
    
        public virtual Estados Estados { get; set; }
        public virtual Familias Familias { get; set; }
        public virtual IVAs IVAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BienesCompuestos> BienesCompuestos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BienesCompuestos> BienesCompuestos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario> Inventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosProveedoresDetalle> PedidosProveedoresDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PresupuestosClientesDetalle> PresupuestosClientesDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cualidades> Cualidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historicos> Historicos { get; set; }
    }
}
