//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturasClientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacturasClientes()
        {
            this.Historicos = new HashSet<Historicos>();
            this.PedidosClientes = new HashSet<PedidosClientes>();
        }
    
        public int Id { get; set; }
        public int TipoFacturaId { get; set; }
        public string CodFactura { get; set; }
        public int IRPFId { get; set; }
        public int EmpleadoId { get; set; }
        public int EstadoId { get; set; }
        public System.DateTime FechaAlta { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual IRPFs IRPFs { get; set; }
        public virtual TiposFacturas TiposFacturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historicos> Historicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosClientes> PedidosClientes { get; set; }
    }
}
