//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGestion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GesemEntities : DbContext
    {
        public GesemEntities()
            : base("name=GesemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationGroups> ApplicationGroups { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Bienes> Bienes { get; set; }
        public virtual DbSet<BienesCompuestos> BienesCompuestos { get; set; }
        public virtual DbSet<CambiosLog> CambiosLog { get; set; }
        public virtual DbSet<Cargos> Cargos { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Cualidades> Cualidades { get; set; }
        public virtual DbSet<DireccionesFacturacion> DireccionesFacturacion { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<Empresas> Empresas { get; set; }
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<FacturasClientes> FacturasClientes { get; set; }
        public virtual DbSet<FacturasProveedores> FacturasProveedores { get; set; }
        public virtual DbSet<Familias> Familias { get; set; }
        public virtual DbSet<FormasEntrega> FormasEntrega { get; set; }
        public virtual DbSet<FormasPago> FormasPago { get; set; }
        public virtual DbSet<Historicos> Historicos { get; set; }
        public virtual DbSet<Idiomas> Idiomas { get; set; }
        public virtual DbSet<Inventario> Inventario { get; set; }
        public virtual DbSet<IRPFs> IRPFs { get; set; }
        public virtual DbSet<IVAs> IVAs { get; set; }
        public virtual DbSet<Locales> Locales { get; set; }
        public virtual DbSet<Localidades> Localidades { get; set; }
        public virtual DbSet<Paises> Paises { get; set; }
        public virtual DbSet<PedidosClientes> PedidosClientes { get; set; }
        public virtual DbSet<PedidosProveedores> PedidosProveedores { get; set; }
        public virtual DbSet<PedidosProveedoresDetalle> PedidosProveedoresDetalle { get; set; }
        public virtual DbSet<Personas> Personas { get; set; }
        public virtual DbSet<PresupuestosClientes> PresupuestosClientes { get; set; }
        public virtual DbSet<PresupuestosClientesDetalle> PresupuestosClientesDetalle { get; set; }
        public virtual DbSet<PresupuestosClientesDetalleAgrupados> PresupuestosClientesDetalleAgrupados { get; set; }
        public virtual DbSet<Proveedores> Proveedores { get; set; }
        public virtual DbSet<Provincias> Provincias { get; set; }
        public virtual DbSet<Recursos> Recursos { get; set; }
        public virtual DbSet<TiposDeCualidades> TiposDeCualidades { get; set; }
        public virtual DbSet<TiposFacturas> TiposFacturas { get; set; }
        public virtual DbSet<TiposPropiedades> TiposPropiedades { get; set; }
    }
}
