//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosClientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PedidosClientes()
        {
            this.Historicos = new HashSet<Historicos>();
            this.FacturasClientes = new HashSet<FacturasClientes>();
        }
    
        public int Id { get; set; }
        public string CodPedido { get; set; }
        public int PresupuestoId { get; set; }
        public int FormaPagoId { get; set; }
        public int FormaEntregaId { get; set; }
        public int UsuarioId { get; set; }
        public int EstadoId { get; set; }
        public System.DateTime FechaAlta { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual FormasEntrega FormasEntrega { get; set; }
        public virtual FormasPago FormasPago { get; set; }
        public virtual PresupuestosClientes PresupuestosClientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historicos> Historicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasClientes> FacturasClientes { get; set; }
    }
}
