//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosProveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PedidosProveedores()
        {
            this.PedidosProveedoresDetalle = new HashSet<PedidosProveedoresDetalle>();
            this.Historicos = new HashSet<Historicos>();
            this.FacturasProveedores = new HashSet<FacturasProveedores>();
        }
    
        public int Id { get; set; }
        public string CodPedido { get; set; }
        public int ProveedorId { get; set; }
        public int EstadoId { get; set; }
        public System.DateTime FechaAlta { get; set; }
    
        public virtual Estados Estados { get; set; }
        public virtual Proveedores Proveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosProveedoresDetalle> PedidosProveedoresDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historicos> Historicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasProveedores> FacturasProveedores { get; set; }
    }
}
