//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresupuestosClientesDetalle
    {
        public int Id { get; set; }
        public int AgrupadoId { get; set; }
        public int BienId { get; set; }
        public double Cantidad { get; set; }
        public int IVAId { get; set; }
        public double Precio { get; set; }
    
        public virtual Bienes Bienes { get; set; }
        public virtual IVAs IVAs { get; set; }
        public virtual PresupuestosClientesDetalleAgrupados PresupuestosClientesDetalleAgrupados { get; set; }
    }
}
