//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresupuestosClientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PresupuestosClientes()
        {
            this.PedidosClientes = new HashSet<PedidosClientes>();
            this.PresupuestosClientesDetalleAgrupados = new HashSet<PresupuestosClientesDetalleAgrupados>();
            this.Historicos = new HashSet<Historicos>();
        }
    
        public int Id { get; set; }
        public string CodPresupuesto { get; set; }
        public int ClienteId { get; set; }
        public int UsuarioId { get; set; }
        public int EstadoId { get; set; }
        public System.DateTime FechaAlta { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Estados Estados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosClientes> PedidosClientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PresupuestosClientesDetalleAgrupados> PresupuestosClientesDetalleAgrupados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historicos> Historicos { get; set; }
    }
}
